const express=require('express');
const userRouter=express()
const userController=require('../controller/user_controller')
const cartController=require('../controller/cartController')
const auth=require('../middleware/auth')

userRouter.get("/",auth.isLogout,auth.checkBlocked,userController.loadHome)
userRouter.get("/home",auth.checkBlocked,userController.loadHome)
userRouter.get("/shop",auth.checkBlocked,userController.loadShop)
userRouter.get('/about',auth.checkBlocked,userController.loadAbout)
userRouter.get("/contact",auth.checkBlocked,userController.loadContact)
userRouter.get('/login',auth.isLogout,userController.loadLogin)
userRouter.post('/login',userController.verifyLogin)
userRouter.get('/signup',auth.checkBlocked,userController.loadSignup)
userRouter.post('/signup',userController.verifySignup)
userRouter.get('/otpVerify',auth.checkBlocked,auth.isLogout,userController.loadOTP)
userRouter.post('/otpVerify',userController.verifyOTP)
userRouter.get('/item',auth.checkBlocked,userController.loadSingleshop)
userRouter.get('/userLogout',auth.checkBlocked,userController.userLogout)
userRouter.get('/forgotPassword',auth.checkBlocked,userController.forgotPass)
userRouter.post('/forgotPassword',userController.forgotPassSendMail)
userRouter.get('/cart',auth.checkBlocked,cartController.loadCart)
userRouter.post('/addToCart',cartController.loadAddCart)
userRouter.post('/removeCart',cartController.removeCart)
userRouter.get('/checkout',auth.checkBlocked,cartController.loadCheckout)
userRouter.post('/verify-payment',cartController.verifyPayment)
userRouter.post('/addAddress',cartController.addAddress)
userRouter.post('/placeOrder',cartController.placeOrder)
userRouter.get('/orderPlaced/:id',auth.checkBlocked,cartController.orderPlaced)
userRouter.get('/profile',auth.checkBlocked,userController.loadProfile)
userRouter.post('/profile',userController.editProfile)
userRouter.get('/profile/changePass',auth.checkBlocked,userController.loadChangePass)
userRouter.post('/profile/changePass',userController.changePassword)
userRouter.get('/orders',auth.checkBlocked,userController.loadOrder)
userRouter.get('/vieworders',auth.checkBlocked,userController.loadViewOrder)
userRouter.post('/cancelOrderStatus',userController.cancelOrderStatus)
userRouter.post('/returnOrderStatus',userController.returnOrderStatus)
userRouter.get('/viewAddress',auth.checkBlocked,userController.loadAddress)
userRouter.get('/userAddAddress',auth.checkBlocked,userController.loadAddAddress)
userRouter.post('/userAddAddress',userController.addAddress)
userRouter.post('/deleteAddress',userController.deleteAddress)
userRouter.get('/editAddress',auth.checkBlocked,userController.loadEditAddress)
userRouter.post('/editAddress',userController.editAddress)
userRouter.post('/updateQuantity',cartController.updateQuantity)




module.exports=userRouter